### ISSUE TITLE
Configurable hostname not supported in PersistentHTTP class

### ISSUE THREAD

**Issue by mrbreaker** [hashicorp/vault-ruby#139]
The  PersistentHTTP class does not support a configurable hostname, although the Client class attempts to set it when it's configured.

```
        if hostname
          @nhp.hostname = hostname
        end
```

**Comment by tomalok** [comment]
Attempting to update my Vault stack, and I'm hitting this as well...
Was working with vault-ruby 0.8.0, FWIW.

```
F, [2017-04-28T20:42:26.989565 #92] FATAL -- : NoMethodError - undefined method `hostname=' for #<Vault::PersistentHTTP:0x007f13cd25ac78> - ["/abc/vendor/bundle/ruby/2.3.0/gems/vault-0.10.0/lib/vault/client.rb:89:in `block in pool'", "/abc/vendor/bundle/ruby/2.3.0/gems/vault-0.10.0/lib/vault/client.rb:83:in `synchronize'", "/abc/vendor/bundle/ruby/2.3.0/gems/vault-0.10.0/lib/vault/client.rb:83:in `pool'", "/abc/vendor/bundle/ruby/2.3.0/gems/vault-0.10.0/lib/vault/client.rb:273:in `request'", "/abc/vendor/bundle/ruby/2.3.0/gems/vault-0.10.0/lib/vault/client.rb:182:in `get'", "/abc/vendor/bundle/ruby/2.3.0/gems/vault-0.10.0/lib/vault/api/sys/init.rb:36:in `init_status'", "./sentinel.rb:76:in `<main>'"]
```

**Comment by tomalok** [comment]
Actually, it wasn't working on 0.8.0 -- I hadn't set `VAULT_TLS_SERVER_NAME` at all, which allowed `VAULT_SKIP_VERIFY` to work as advertised.

**Comment by acranox** [comment]
I'm seeing this as well.  There's been no updates on this issue in almost 4 months.  It's not clear to me what the correct resolution is.

**Comment by mrbreaker** [comment]
It might be possible by manually adding the "Host:" header to the http object. However, the certificate will still be validated against the address and not to the host name.

**Comment by evanphx** [comment]
The :hostname option isn't working at present so I've removed the offending code. For the next release, the hostname option won't do anything.
